# Generated by Django 5.2 on 2025-04-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_mindtrack', '0002_alter_usuario_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('perguntaID', models.AutoField(primary_key=True, serialize=False)),
                ('pergunta', models.CharField(max_length=255)),
            ],
        ),
    ]
