# Generated by Django 5.2 on 2025-04-06 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto_mindtrack', '0003_pergunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('formularioID', models.AutoField(primary_key=True, serialize=False)),
                ('data_resposta', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto_mindtrack.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.BooleanField()),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto_mindtrack.formulario')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto_mindtrack.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('resultadoID', models.AutoField(primary_key=True, serialize=False)),
                ('pontuacao', models.IntegerField()),
                ('estratificacao', models.CharField(max_length=50)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto_mindtrack.formulario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto_mindtrack.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='FormularioPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto_mindtrack.formulario')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto_mindtrack.pergunta')),
            ],
            options={
                'unique_together': {('formulario', 'pergunta')},
            },
        ),
    ]
